-- =========================================================================
-- IMPOSE MAGAZINE — SEED COVERS
-- Synchronisation des 26 couvertures officielles vers Supabase
-- =========================================================================
-- 1. Collez ce script dans le SQL Editor de votre dashboard Supabase :
--    https://supabase.com/dashboard/project/uwrcztmhsobwsylsltrv/sql/new
-- 2. Cliquez sur "Run"
-- =========================================================================

-- Nettoyage et réinitialisation
DELETE FROM public.covers;
ALTER SEQUENCE public.covers_id_seq RESTART WITH 1;

-- Insertion des 26 couvertures (URLs CDN Cloudflare / Supabase Storage ultra-rapides)
INSERT INTO public.covers (number, title, person, date, image_url, description, featured, order_index) VALUES
  ('N°31', 'L''impact comme moteur : Quand le business devient une solution pour tous', 'Joseph-Olivier Biley', 'Septembre 2026', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/josephbiley.jpg', 'Joseph-Olivier Biley — Co-Founder & CEO, Jool International. 125 Millions de dollars ATIDI pour l''investissement en Afrique.', true, 1),
  ('N°30', 'Tout devient digital : Comprendre et maîtriser le virage incontournable', 'Alex Zan Bi', 'Août 2026', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/alex_zan_bi.jpg', 'Alex Zan Bi — Entrepreneur Digital & Créateur de Contenu (+300k abonnés). Fondateur Lewa Space & Cofondateur GetMedford.', true, 2),
  ('N°29', 'Quand la technologie tente de structurer l''informel africain', 'Moro Application', 'Mai 2026', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/moro_application.jpg', 'Inclusion financière, données et éducation financière : une nouvelle approche pour rendre les micro-entrepreneurs visibles et finançables. 1,7 Milliard FCFA dans l''UEMOA.', true, 3),
  ('N°28', 'Africa''s Business Heroes — Le nouveau pouvoir féminin de l''innovation', 'Gwladys Alahassa', 'Avril 2026', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/gwladys.jpg', 'Gwladys Alahassa — Directrice Générale Qotto Bénin. Elles déplacent les lignes : le nouveau pouvoir féminin de l''innovation.', true, 4),
  ('N°27', 'L''architecte de la réputation', 'El Hadji Ndoye', 'Mars 2026', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/ndoye.jpg', 'El Hadji Ndoye — Expert en Personal Branding pour Entrepreneurs & CEOs. Le CEO qui façonne les leaders de demain. Africa''s Business Heroes 2026.', true, 5),
  ('N°26', 'Transformer la passion en entreprise : Le pari lucide des créatifs africains', 'Mohamed Aly Diabaté', 'Février 2026', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/mohamed_aly_diabate_.jpg', 'Mohamed Aly Diabaté — Filmmaker, Photojournalist & Manager Visualis Africa. 29 500 Milliards USD de richesses minières & Initiative IA Bill Gates / OpenAI.', true, 6),
  ('N°25', 'Pourquoi les investisseurs misent sur la finance africaine ?', 'Jonathan Ouedraogo', 'Janvier 2025', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/ouedraogo.jpg', 'Jonathan Ouedraogo — Banque et Ingénierie Financière, Expert E-commerce. SEDAP & Programme TEF.', false, 7),
  ('N°24', 'Vision, défis et leadership de l''Amazone de l''Énergie', 'Florence Eba', 'Décembre 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/florence.jpg', 'Florence Eba — Snr Consultant & Director at Venture Konect. Le Sénégal soutient la Banque Africaine de l''Énergie.', false, 8),
  ('N°23', 'L''écosystème des startups en Côte d''Ivoire', 'Alexia Amicha', 'Août 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/alexia.jpg', 'Alexia Amicha — Sous-directrice du Développement de l''Entrepreneuriat et des Startups Technologiques.', false, 9),
  ('N°22', 'Transforming life in Africa & CleanTech', 'Deborah Gael', 'Octobre 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/impose___cover_deborah.jpg', 'Deborah Gael — Co-Founder and COO of Koolboks. Réfrigération solaire et accélération des énergies durables.', false, 10),
  ('N°22', '$145 million to boost energy & Finance internationale', 'Brian Hurfet', 'Octobre 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/bryan.jpg', 'Brian Hurfet — CEO de BHB Investments & Business Services et African Insights Academy. Ancien banquier d''affaires.', false, 11),
  ('N°21', 'L''inclusion financière dans le contexte africain', 'Darly Nguema', 'Septembre 2025', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/darly_nguema.jpg', 'Darly Nguema — Analyste financière. L''accès universel et équitable aux services financiers numériques abordables.', false, 12),
  ('N°21', 'L''univers remarquable des startups en Afrique', 'Alex Degny', 'Juin 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/alexdegny.jpg', 'Alex Degny — Président du CI20. 20 startups numériques représentent la Côte d''Ivoire à l''international.', false, 13),
  ('N°20', 'Fintech : Vers une révolution inclusive de la finance en Afrique de l''Ouest', 'Régis Zagbadi', 'Août 2025', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/_zagbadi.jpg', 'Régis Zagbadi — Expert Risques & Compliance FinTech UEMOA | Fondateur IZAQA. Bientôt les paiements instantanés pour tous, Mobile Money et PI-SPI.', true, 14),
  ('N°19', 'L''art contemporain, entre révolte esthétique et questionnements identitaires', 'Olatidoye Iburaim Olaniyi (Grouilleur 3.0)', 'Juillet 2025', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/grouilleur3.0.jpg', 'Olatidoye Iburaim Olaniyi — Photographe professionnel. Prix Pierre Castel 2025 : « DJOLI » sacré vainqueur. Le champ du producteur devient notre frigo.', false, 15),
  ('N°18', 'La startup africaine qui redéfinit la mobilité urbaine', 'Wilfried Adingra', 'Juin 2025', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/wilfried_adingra.jpg', 'Wilfried Adingra — Founder & CEO at GLSAfrica. Avec plus de 50 Millions de FCFA préparez l''avenir, incubez l''innovation & Un bond en avant dans l''IA.', false, 16),
  ('N°17', 'L''IA au service de l''agriculture durable en Afrique', 'Daniel Oulaï', 'Mai 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/daniel_oulai.jpg', 'Daniel Oulaï — PDG de la GRAINOTECH SAS, entrepreneur social engagé. +7000 inscrits en 2025 & Google s''associe à des acteurs tech africains.', false, 17),
  ('N°16', '« La littérature est un outil puissant pour s''enrichir »', 'Charlène Danon', 'Avril 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/charlene_danon.jpg', 'Charlène Danon — Journaliste, scénariste-productrice et écrivaine. 49 jeunes bénéficient de 36 millions à Gagnoa & Gérez votre projet avec MORO.', false, 18),
  ('N°15', 'Puissance féminine : Entre ambition et audace', 'Mylène Amon & Charlène Valmorin', 'Mars 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/mylen___charlene.jpg', 'Mylène Amon (Paper-artist) & Charlène Valmorin (My Place Events & AbidjanaisesInTech). 4 Startups fintech accompagnées à hauteur de 1 milliard.', false, 19),
  ('N°14', '« C''est le meilleur héritage que je puisse laisser à cette jeunesse »', 'Assalé Tiémoko', 'Février 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/assale__tie_moko.jpg', 'Assalé Tiémoko — Député-Maire de Tiassalé et Président de mouvement ADCI. CI20 MEETUP : Un tournant décisif pour les startups ivoiriennes.', false, 20),
  ('N°12', 'Médias, Innovation & Technologie IA transforment nos sociétés africaines', 'Israël Guébo', 'Décembre 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/israel_guebo.jpg', 'Israël Guébo — Vice-Président ADCI, Consultant en communication et médias. 20 Jeunes entrepreneurs en Corée du Sud & Sommet SACH 2025.', false, 21),
  ('N°11', '2 Milliards disponibles pour la jeunesse ivoirienne', 'Stéphane Bolou', 'Novembre 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/ste_phane_bolou.jpg', 'Stéphane Bolou — Délégué Exécutif #Ci20 | Directeur Fund Management du Fonds Startup Boost Capital.', false, 22),
  ('N°10', 'Des institutions s''engagent dans l''autonomisation des jeunes', 'Olga Djadji', 'Octobre 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/olga_djadji.jpg', 'Olga Djadji — Présidente de la Fondation BKD (Bénédicte Janine Kacou Diagou). Impacter un million de jeunes.', false, 23),
  ('N°07', 'L''impact de la digitalisation sur la jeunesse africaine', 'Polus Agathon', 'Juillet 2024', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/agathonpolusa.jpg', 'Polus Agathon — Spécialiste en Communication Digitale, Formateur certifié Méta.', false, 24),
  ('N°06', 'Passionjob, le chemin d''accès à votre épanouissement !', 'Axelle Aurore', 'Juin 2023', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/axel_aurore.jpg', 'Axelle Aurore — Choisir de vivre selon ses passions est un passeport pour la réussite ! #Mentorat (Re)Orientation Professionnelle.', false, 25),
  ('N°03', '100 personnalités qui ont changé l''Afrique', 'Jemima Kessie', 'Mars 2023', 'https://uwrcztmhsobwsylsltrv.supabase.co/storage/v1/object/public/impose-media/covers/coverimposejemima_copie.jpg', 'Jemima Kessie — Nouvelle génération de communicants en faveur des bonnes conditions des femmes.', false, 26);
